@startuml
abstract class com.sbnvw.artemis.animal_kingdom.treeOfLife.Animal
abstract class com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.Mammalia
abstract class com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.Carnivora
annotation java.lang.Override
annotation javafx.fxml.FXML
class com.sbnvw.artemis.MainApp
class com.sbnvw.artemis.acount.Acount
class com.sbnvw.artemis.animal_kingdom.traits.diet.Eats_Meat
class com.sbnvw.artemis.animal_kingdom.traits.diet.Eats_Plants
class com.sbnvw.artemis.animal_kingdom.traits.fur.Feathers
class com.sbnvw.artemis.animal_kingdom.traits.fur.Long_Hear
class com.sbnvw.artemis.animal_kingdom.traits.fur.Short_Hear
class com.sbnvw.artemis.animal_kingdom.treeOfLife.Birds.Birds
class com.sbnvw.artemis.animal_kingdom.treeOfLife.Birds.parrots.Parrots
class com.sbnvw.artemis.animal_kingdom.treeOfLife.Birds.parrots.oldWorldParrots.OldWorldParrots
class com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.canidae.Canidae
class com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.canidae.dogs.Dog
class com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.cats.Cats
class com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.cats.smallCats.Cat
class com.sbnvw.artemis.controllers.AdminMenuController
class com.sbnvw.artemis.controllers.LoginPageController
class com.sbnvw.artemis.controllers.MainSearchWindowController
class com.sbnvw.artemis.controllers.MainWindowController
class com.sbnvw.artemis.controllers.MakeAnimalPageController
class com.sbnvw.artemis.controllers.PreviewWindowController
class java.io.IOException
class java.net.URL
class java.util.ArrayList
class java.util.Observable
class java.util.ResourceBundle
class javafx.application.Application
class javafx.collections.ObservableList
class javafx.event.ActionEvent
class javafx.fxml.FXMLLoader
class javafx.geometry.Rectangle2D
class javafx.scene.Parent
class javafx.scene.Scene
class javafx.scene.control.Button
class javafx.scene.control.ListView
class javafx.scene.control.MenuItem
class javafx.scene.control.PasswordField
class javafx.scene.control.TextArea
class javafx.scene.control.TextField
class javafx.scene.image.ImageView
class javafx.scene.input.KeyCode
class javafx.scene.input.KeyEvent
class javafx.scene.input.MouseEvent
class javafx.scene.layout.AnchorPane
class javafx.scene.layout.BorderPane
class javafx.scene.layout.Pane
class javafx.scene.layout.VBox
class javafx.scene.text.Text
class javafx.stage.Screen
class javafx.stage.Stage
interface com.sbnvw.artemis.animal_kingdom.traits.diet.Diet
interface com.sbnvw.artemis.animal_kingdom.traits.fur.Fur
interface javafx.fxml.Initializable
com.sbnvw.artemis.animal_kingdom.treeOfLife.Animal ..> java.lang.Override
com.sbnvw.artemis.animal_kingdom.treeOfLife.Animal ..> com.sbnvw.artemis.animal_kingdom.traits.diet.Diet
com.sbnvw.artemis.animal_kingdom.treeOfLife.Animal ..> com.sbnvw.artemis.animal_kingdom.traits.fur.Fur
com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.Mammalia --|> com.sbnvw.artemis.animal_kingdom.treeOfLife.Animal
com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.Mammalia ..> com.sbnvw.artemis.animal_kingdom.traits.diet.Eats_Meat
com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.Carnivora --|> com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.Mammalia
com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.Carnivora ..> java.lang.Override
com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.Carnivora ..> com.sbnvw.artemis.animal_kingdom.traits.diet.Eats_Meat
com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.Carnivora ..> com.sbnvw.artemis.animal_kingdom.traits.diet.Diet
com.sbnvw.artemis.MainApp ..> java.lang.Override
com.sbnvw.artemis.MainApp ..> com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.cats.smallCats.Cat
com.sbnvw.artemis.MainApp ..> com.sbnvw.artemis.controllers.MainSearchWindowController
com.sbnvw.artemis.MainApp ..> com.sbnvw.artemis.controllers.MainWindowController
com.sbnvw.artemis.MainApp ..> java.io.IOException
com.sbnvw.artemis.MainApp --|> javafx.application.Application
com.sbnvw.artemis.MainApp ..> javafx.fxml.FXMLLoader
com.sbnvw.artemis.MainApp ..> javafx.geometry.Rectangle2D
com.sbnvw.artemis.MainApp ..> javafx.scene.Parent
com.sbnvw.artemis.MainApp ..> javafx.scene.Scene
com.sbnvw.artemis.MainApp ..> javafx.scene.layout.Pane
com.sbnvw.artemis.MainApp ..> javafx.stage.Screen
com.sbnvw.artemis.MainApp ..> javafx.stage.Stage
com.sbnvw.artemis.animal_kingdom.traits.diet.Eats_Meat ..> java.lang.Override
com.sbnvw.artemis.animal_kingdom.traits.diet.Eats_Meat --|> com.sbnvw.artemis.animal_kingdom.traits.diet.Diet
com.sbnvw.artemis.animal_kingdom.traits.diet.Eats_Plants ..> java.lang.Override
com.sbnvw.artemis.animal_kingdom.traits.diet.Eats_Plants --|> com.sbnvw.artemis.animal_kingdom.traits.diet.Diet
com.sbnvw.artemis.animal_kingdom.traits.fur.Feathers ..> java.lang.Override
com.sbnvw.artemis.animal_kingdom.traits.fur.Feathers --|> com.sbnvw.artemis.animal_kingdom.traits.fur.Fur
com.sbnvw.artemis.animal_kingdom.traits.fur.Long_Hear ..> java.lang.Override
com.sbnvw.artemis.animal_kingdom.traits.fur.Long_Hear --|> com.sbnvw.artemis.animal_kingdom.traits.fur.Fur
com.sbnvw.artemis.animal_kingdom.traits.fur.Short_Hear ..> java.lang.Override
com.sbnvw.artemis.animal_kingdom.traits.fur.Short_Hear --|> com.sbnvw.artemis.animal_kingdom.traits.fur.Fur
com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.canidae.Canidae --|> com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.Carnivora
com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.canidae.dogs.Dog --|> com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.canidae.Canidae
com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.cats.Cats --|> com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.Carnivora
com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.cats.Cats ..> com.sbnvw.artemis.animal_kingdom.traits.diet.Diet
com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.cats.smallCats.Cat --|> com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.cats.Cats
com.sbnvw.artemis.controllers.AdminMenuController ..> java.lang.Override
com.sbnvw.artemis.controllers.AdminMenuController ..> java.net.URL
com.sbnvw.artemis.controllers.AdminMenuController ..> java.util.ResourceBundle
com.sbnvw.artemis.controllers.AdminMenuController --|> javafx.fxml.Initializable
com.sbnvw.artemis.controllers.LoginPageController ..> java.lang.Override
com.sbnvw.artemis.controllers.LoginPageController ..> javafx.fxml.FXML
com.sbnvw.artemis.controllers.LoginPageController ..> com.sbnvw.artemis.MainApp
com.sbnvw.artemis.controllers.LoginPageController ..> java.net.URL
com.sbnvw.artemis.controllers.LoginPageController ..> java.util.ResourceBundle
com.sbnvw.artemis.controllers.LoginPageController ..> javafx.event.ActionEvent
com.sbnvw.artemis.controllers.LoginPageController ..> javafx.scene.control.Button
com.sbnvw.artemis.controllers.LoginPageController ..> javafx.scene.control.PasswordField
com.sbnvw.artemis.controllers.LoginPageController ..> javafx.scene.control.TextField
com.sbnvw.artemis.controllers.LoginPageController ..> javafx.scene.input.KeyCode
com.sbnvw.artemis.controllers.LoginPageController ..> javafx.scene.input.KeyEvent
com.sbnvw.artemis.controllers.LoginPageController ..> javafx.scene.layout.VBox
com.sbnvw.artemis.controllers.LoginPageController --|> javafx.fxml.Initializable
com.sbnvw.artemis.controllers.MainSearchWindowController ..> com.sbnvw.artemis.animal_kingdom.treeOfLife.Animal
com.sbnvw.artemis.controllers.MainSearchWindowController ..> java.lang.Override
com.sbnvw.artemis.controllers.MainSearchWindowController ..> javafx.fxml.FXML
com.sbnvw.artemis.controllers.MainSearchWindowController ..> com.sbnvw.artemis.MainApp
com.sbnvw.artemis.controllers.MainSearchWindowController ..> com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.canidae.dogs.Dog
com.sbnvw.artemis.controllers.MainSearchWindowController ..> com.sbnvw.artemis.animal_kingdom.treeOfLife.mammalia.carnivora.cats.smallCats.Cat
com.sbnvw.artemis.controllers.MainSearchWindowController ..> java.net.URL
com.sbnvw.artemis.controllers.MainSearchWindowController ..> java.util.ArrayList
com.sbnvw.artemis.controllers.MainSearchWindowController ..> java.util.Observable
com.sbnvw.artemis.controllers.MainSearchWindowController ..> java.util.ResourceBundle
com.sbnvw.artemis.controllers.MainSearchWindowController ..> javafx.collections.ObservableList
com.sbnvw.artemis.controllers.MainSearchWindowController ..> javafx.event.ActionEvent
com.sbnvw.artemis.controllers.MainSearchWindowController ..> javafx.scene.control.ListView
com.sbnvw.artemis.controllers.MainSearchWindowController ..> javafx.scene.input.MouseEvent
com.sbnvw.artemis.controllers.MainSearchWindowController ..> javafx.scene.layout.AnchorPane
com.sbnvw.artemis.controllers.MainSearchWindowController --|> javafx.fxml.Initializable
com.sbnvw.artemis.controllers.MainWindowController ..> java.lang.Override
com.sbnvw.artemis.controllers.MainWindowController ..> javafx.fxml.FXML
com.sbnvw.artemis.controllers.MainWindowController ..> com.sbnvw.artemis.MainApp
com.sbnvw.artemis.controllers.MainWindowController ..> java.net.URL
com.sbnvw.artemis.controllers.MainWindowController ..> java.util.ResourceBundle
com.sbnvw.artemis.controllers.MainWindowController ..> javafx.event.ActionEvent
com.sbnvw.artemis.controllers.MainWindowController ..> javafx.scene.control.MenuItem
com.sbnvw.artemis.controllers.MainWindowController ..> javafx.scene.layout.AnchorPane
com.sbnvw.artemis.controllers.MainWindowController ..> javafx.scene.layout.BorderPane
com.sbnvw.artemis.controllers.MainWindowController --|> javafx.fxml.Initializable
com.sbnvw.artemis.controllers.MakeAnimalPageController ..> java.lang.Override
com.sbnvw.artemis.controllers.MakeAnimalPageController ..> java.net.URL
com.sbnvw.artemis.controllers.MakeAnimalPageController ..> java.util.ResourceBundle
com.sbnvw.artemis.controllers.MakeAnimalPageController --|> javafx.fxml.Initializable
com.sbnvw.artemis.controllers.PreviewWindowController ..> java.lang.Override
com.sbnvw.artemis.controllers.PreviewWindowController ..> javafx.fxml.FXML
com.sbnvw.artemis.controllers.PreviewWindowController ..> java.net.URL
com.sbnvw.artemis.controllers.PreviewWindowController ..> java.util.ResourceBundle
com.sbnvw.artemis.controllers.PreviewWindowController ..> javafx.scene.control.TextArea
com.sbnvw.artemis.controllers.PreviewWindowController ..> javafx.scene.image.ImageView
com.sbnvw.artemis.controllers.PreviewWindowController ..> javafx.scene.text.Text
com.sbnvw.artemis.controllers.PreviewWindowController --|> javafx.fxml.Initializable
@enduml